import { useState } from "react";
import Button from "../components/Button";
import Modal from "../components/Modal";

function ModalPage() {

    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    } 

    const handleClose = () => {
        setShowModal(false)
    };

    const actionBar = <div>
        <Button onClick={handleClose} primary>I Accept</Button>
        </div>;

    const modal = <Modal onClose={handleClose} actionBar={actionBar}>
            <p>Here is an important agreement for you to accept</p>
    </Modal>;

    return (
        <div>
            
            
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo rem eveniet pariatur optio dolor repudiandae quis consequatur necessitatibus quasi aliquid quas molestias, quos accusamus. Nostrum eius tempora voluptatem eaque laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, iusto! Amet odit ducimus repellat, cumque libero maxime soluta distinctio mollitia a, facilis voluptatibus quia saepe, veniam maiores asperiores deserunt quod. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Itaque vel ad optio ipsam ea? Quaerat nemo odit cum consequatur hic laboriosam nesciunt? Eveniet magni ullam itaque nisi totam praesentium unde?</p>
      
    <Button onClick={handleClick} primary >
                Open Modal
            </Button>
            {showModal && modal}

        </div>
    );
}

export default ModalPage;